### ISSUE TITLE
✅ Tests

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/algaeff#1]
It would be great to (1) figure out how to effectively test effectful code, and (2) write some basic tests and demonstrations!

**Comment by favonia** [comment]
My current plan for `Reader`/`State` is to use QuickCheck to verify their equational theory. Not sure about `Mutex`.

**Comment by favonia** [comment]
@jonsterling An open problem seems to be proving that the imperative, reference-based implementation (ours) is equivalent to the functional one with shallow handlers?
