### ISSUE TITLE
Coordinated releases with algaeff 2.0.0

### ISSUE THREAD

**Issue by favonia** [RedPRL/algaeff#26]
@jonsterling proposed a plan to coordinate releases in #24 in the face of the next major release with breaking changes. Let's continue the conversation here.

- asai: https://github.com/RedPRL/asai/pull/132
- yuujinchou: https://github.com/RedPRL/yuujinchou/pull/123
- forester: ?

**Comment by favonia** [comment]
@jonsterling algaeff 2.0.0 and yuujinchou 5.2.0 are ready! So potentially you could start updating forester now...

**Comment by jonsterling** [comment]
Thanks @favonia ! I'm cutting a new version of forester that adds the upper bounds, and then once your new packages appear on opam I will upgrade forester.

**Comment by favonia** [comment]
@jonsterling I thought you can just update the existing OPAM files in the OPAM repository and maybe that would be easier (?)

**Comment by favonia** [comment]
@jonsterling Actually, I have perhaps a better plan: I have figured out how to release multiple packages at once. I can release all four OPAM packages when you are ready.

**Comment by jonsterling** [comment]
Cool :) If you can wait until my PR is merged (https://github.com/ocaml/opam-repository/pull/24735), then I will be very happy

**Comment by favonia** [comment]
Now the coast in clear but I want to release everything with asai 0.3.0 altogether!

**Comment by favonia** [comment]
Done by https://github.com/ocaml/opam-repository/pull/24738.
