### ISSUE TITLE
Should the functors be generative

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/algaeff#31]
I noticed that the functors in this library are applicative, but I don't think that's the right semantics... Is it?

**Comment by favonia** [comment]
OCaml makes everything very applicative until you start to use [some language extension.](https://ocaml.org/manual/5.2/generativefunctors.html) So the question is whether we should push the button...

**Comment by jonsterling** [comment]
@favonia I'm not sure what you mean by "language extension" --- the ability to form generative functors has been present in OCaml for several years. You do it by adding a null argument to the functor.

My concern is basically that the semantics of an applicative functor that adds new constructors to a datatype are completely unclear to me, so I am worried that the code as-written may be kind of underspecified...

**Comment by jonsterling** [comment]
Oh, I see, this is described in the docs as an extension... But basically the situation is OCaml supports both applicative and generative functors, and if these ones are going to be applicative, it's mandatory for us to have a mental model for WTF it means to generate fresh data constructors inside one. (Unless the semantics of OCaml is like Dreyer-Harper-etc., where there is some automatic inference of purity to determine whether something is applicative? I'm not sure)

**Comment by jonsterling** [comment]
After playing in the repl with  "applicative" functors, it seems the semantics is very strange, but maybe safe. If you call an applicative functor twice (even with the same type argument), the initialisation effect (e.g. generating a new constructor, or printing to the console) is run twice. 

It is a bit mind-bending to figure out if this behaviour is desirable... Overall, in the presence of effects like this, I think that the applicative semantics are really messed up. I think, for example, if OCaml did not have the syntactic restriction that you can't project a value from an expression like `M(X)` directly without binding that to a module variable, it would be easy to come up with examples where the applicative semantics defies intuitions.

**Comment by favonia** [comment]
Yes, the applicative/generative difference in OCaml only affects whether two types are equal AFAIK. I agree with you in principle. The only roadblock is that this will be a breaking change, and I'm not sure what would _not_ be generative in the presence of effects, and we will write lots of `()`...

**Comment by jonsterling** [comment]
Maybe we should leave it as is, since no new types are exported by these modules...
